### DISCUSSION TITLE
How to use this with non-absolute path?

### DISCUSSION THREAD

**Discussion by MSWS** [SinTan1729/chhoto-url#8] [Q&A]
**Is your feature request related to a problem? Please describe.**
I am attempting to host this behind an Nginx server alongside a main website (eg: https://website.com/s would take me to the dashboard, and https://website.com/s/short1 would be a possible short URL).
Setting a straightforward redirect from the /s path to the docker container leads to a 404 page error.

**Describe the solution you'd like**
Ideally setting the `site-url` within the environment vars should make it automagically work with the appropriate Nginx config.

**Describe alternatives you've considered**
I'm fairly inexperienced with Nginx, however I have tried modifying the URL path on its end, and I still came up with a 404 error. Ideally I should be able to either do this through the app's settings, or through Nginx.

**Additional context**
This is my current nginx config which results in a 404 error.
```js
location /s {
    return 301 $scheme://$host/s/;
}

location ^~ /s/ {
    include /config/nginx/proxy.conf;
    include /config/nginx/resolver.conf;
    set $upstream_app chhoto-url;
    set $upstream_port 4567;
    set $upstream_proto http;
    proxy_pass $upstream_proto://$upstream_app:$upstream_port;
}
```

![error image](https://img.msws.xyz/img/d1a99d0e069d35be.png)

**Comment by SinTan1729** [comment]
Hi @MSWS, I'm not an expert with Nginx either, but I was able to make it work under caddy inside a subdirectory as is your usecase. The following works with caddy:
```caddyfile
@test host test.mydomain.com
handle @test {
    redir /s /s/
    rewrite /api* /s{uri}
    handle_path /s* {
        reverse_proxy chhoto-url-dev:4567
    }
}
```
where the service is assumed to be at `https://mydomain.com/s/` and the container is `chhoto-url-dev`. I'm sorry that I can't help you with your Nginx config, but I'm sure that you can get help in their forums. Let them know that this caddy config is known to work, and I'm sure someone will come up with a way to replicate it in Nginx.

Edit: Never mind, this will cause some issues if you have other services. I guess I can make small modifications to the js file to make it work.

**Comment by SinTan1729** [comment]
I just pushed the commit d278021e1b32287deb3aa7ece0c53b1c8c603be5, which should fix your issue. Can you try it out? Using the `dev` tag for your docker image should give you this commit. (Also, make sure your server isn't caching `script.js`. I spent quite a while trying to figure out why it's not serving the correct file.)

It should now just work with
```
@test host test.mydomain.com
handle @test {
    redir /s /s/
    handle_path /s* {
        reverse_proxy chhoto-url-dev:4567
    }
}
```
You still need to figure out how to handle the subdirectory properly in Nginx, that's not something I can fix from my side.

**Comment by MSWS** [comment]
Thanks for the response!

I've manually built the code just to double-check, and have cache disabled through Cloudflare. Still running into the 404 code error with the following config:

```js
location /s {
    return 301 /s/;
}

location /s/ {
    include /config/nginx/proxy.conf;
    include /config/nginx/resolver.conf;
    set $upstream_app chhoto-url;
    set $upstream_port 4567;
    set $upstream_proto http;
    proxy_pass $upstream_proto://$upstream_app:$upstream_port;
    proxy_set_header Host $host;
}
```

```yml
services:
    chhoto-url:
        build: .
        restart: unless-stopped
        container_name: chhoto-url
        ports:
            - 4567:4567
        environment:
            # Change if you want to mount the database somewhere else
            # In this case, you can get rid of the db volume below
            # and instead do a mount manually by specifying the location
            - db_url=/data/urls.sqlite
            - site_url="https://website.com/s/"

            - password=${password}
```
