### ISSUE TITLE
Unable to open database error after updating to v5.4.4

### ISSUE THREAD

**Issue by dhanadhan** [SinTan1729/chhoto-url#31]
**Describe the bug**
My docker container auto updated to the latest 5.4.4 and I was not able to login anymore. Looking at the logs, I am getting the below errors. Tried what I could to fix it, but nothing worked. I then deleted the docker stack and reinstalled, but I am getting the same error on the fresh install using the new docker compose. 

`Unable to open database!: SqliteFailure(Error { code: CannotOpen, extended_code: 14 }, Some("unable to open database file: urls.sqlite"))
note: run with RUST_BACKTRACE=1 environment variable to display a backtrace
thread 'main' panicked at /cargo/registry/src/index.crates.io-6f17d22bba15001f/actix-server-2.5.0/src/worker.rs:476:27:
called 'Result::unwrap()' on an 'Err' value: RecvError`

**To Reproduce**
- Install through docker compose

**Expected behavior**
Login and use the app

**Which version of Chhoto-URL are you experiencing the problem on?**
Latest - 5.4.4

**Can you reproduce the issue in the latest version?**
Yes

**Desktop (please complete the following information):**
 - Linux/Docker

**Comment by SinTan1729** [comment]
Hi, can you post a copy of your docker compose file?

**Comment by dhanadhan** [comment]
> Hi, can you post a copy of your docker compose file?
 
 Here it is:

```
services:
    chhoto-url:
        image: sintan1729/chhoto-url:latest
        restart: unless-stopped
        network_mode: bridge
        container_name: chhoto-url
        ports:
            - 4567:4567
        environment:
            # Change if you want to mount the database somewhere else.
            # In this case, you can get rid of the db volume below
            # and instead do a mount manually by specifying the location.
            # - db_url=/urls.sqlite

            # Change it in case you want to set the website name
            # displayed in front of the shorturls, defaults to
            # the hostname you're accessing it from.
            - site_url=http://192.168.1.95:4567/

            - password=TopSecret

            # Pass the redirect method, if needed. TEMPORARY and PERMANENT
            # are accepted values, defaults to PERMANENT.
            # - redirect_method=TEMPORARY
            
            # By default, the auto-generated pairs are adjective-name pairs.
            # If you want UIDs, please change slug_style to UID.
            # Supported values for slug_style are Pair and UID.
            # The length is 8 by default, and a minimum of 4 is allowed.
            # - slug_style=Pair
            # - slug_length=8
            
            # In case you want to provide public access to adding links (and not 
            # delete, or listing), change the following option to Enable.
            # - public_mode=Disable
            
            # By default, the server sends no Cache-Control headers. You can supply a 
            # comma separated list of valid header as per RFC 7234 §5.2 to send those
            # headers instead.
            # - cache_control_header=no-cache, private
        volumes:
            - ./urls.sqlite:/urls.sqlite
```
