### ISSUE TITLE
"unable to open database file: urls.sqlite" on latest (5.4.4)

### ISSUE THREAD

**Issue by sakkarose** [SinTan1729/chhoto-url#32]
**Describe the bug**
```
thread 'actix-rt|system:0|arbiter:0' panicked at src/database.rs:82:37:
Unable to open database!: SqliteFailure(Error { code: CannotOpen, extended_code: 14 }, Some("unable to open database file: urls.sqlite"))
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at /cargo/registry/src/index.crates.io-6f17d22bba15001f/actix-server-2.5.0/src/worker.rs:476:27:
called `Result::unwrap()` on an `Err` value: RecvError
```

**To Reproduce**
Composing with latest image.

**Expected behavior**
The app starts normally.

**Screenshots**

**Which version of Chhoto-URL are you experiencing the problem on?**
latest (5.4.4)

**Can you reproduce the issue in the latest version?**
Yes (It starts in the latest version).

**Additional context**
My docker-compose
```
services:
    chhoto-url:
        image: sintan1729/chhoto-url:latest
        restart: unless-stopped
        container_name: chhoto-url
        ports:
            - 4567:4567
        environment:
            - site_url=https://...
            - password=...
            - redirect_method=TEMPORARY
            - slug_style=Pair
            - slug_length=8
            - public_mode=Disable
            - cache_control_header=no-cache, private
        volumes:
            - db:/urls.sqlite

volumes:
    db:
```
